<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <VersionPrefix>1.0.0</VersionPrefix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
  </ItemGroup>


  <ItemGroup>
    <Using Include="DiffCode.CommonEntities.Abstractions.Case" Static="true" />
    <Using Include="DiffCode.CommonEntities.Abstractions" />
    <Using Include="DiffCode.CommonEntities.Interfaces" />
  </ItemGroup>

</Project>
